# Generated by Django 5.0.6 on 2024-05-16 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=40)),
                ('sobrenome', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('data_de_nascimento', models.DateField()),
            ],
        ),
    ]
